### ISSUE TITLE
Actions has been renamed to winterjung/split.

### ISSUE THREAD

**Issue by irfanfadhilahkp** [JungWinter/split#23]
I have issue when running github action, for detail error you can see the screenshot.
<img width="713" alt="image" src="https://github.com/winterjung/split/assets/129042690/d9a9c1a1-9b21-4c5d-b39a-496dde4986df">

**Comment by amansinghal0** [comment]
we are seeing the same issue in our builds. is there any solution to this?

**Comment by andy-lawler-sbg** [comment]
Same issue currently.

**Comment by aman-singhal-alight** [comment]
@andy-lawler-sbg rename your repo to winterjung/split@v2 .  seems like the owner has changed the name

**Comment by winterjung** [comment]
@irfanfadhilahkp @andy-lawler-sbg Sorry folks. I recently changed my github name to `winterjung`. After changing the name, the `JungWinter/split` repo was redirected to `winterjung/split`, so I thought there would be no problem. Changing the actions name to `winterjung/split@v2` as mentioned above will solve the problem.
