### ISSUE TITLE
Fix typo "seperator" => "separator"

### ISSUE THREAD

**Issue by RichardDally** [JungWinter/split#4]
Problem is: by replacing this keyword it will break on client side...

**Comment by winterjung** [comment]
Thanks for reporting mistypo! To prevent client breaking, I'll add addtional input as `sep`**`a`**`rator`. `sep`**`e`**`rator` will remains until `v2`. Do you think it works well?

**Comment by RichardDally** [comment]
I guess so.

**Comment by winterjung** [comment]
Fixed in #6
